### ISSUE TITLE
Where can i find the file "nextstrain/nextstrain_selected-WGS-for-tree-plus-A02479075_timetree.nwk"?

### ISSUE THREAD

**Issue by liamxg** [flu-crew/h3-iva-evolution#2]

**Comment by tkanderson** [comment]
@mnneveau This appears to be a required input file for Figure 3 gene constellation tree. Can you upload into data_collection folder. Thanks

**Comment by tkanderson** [comment]
> @arendsee @markin-alex @DavidEHufnagel

@liamxg None of these people are associated with the repo. I have redirected your query.

**Comment by mnneveau** [comment]
@liamxg files have been uploaded to Figure3 folder in the data_collection folder. Thanks.
